/** Canonical list of tool slugs for project workspace */
export const TOOL_SLUGS = [
  'qr-generator',
  'ab-test',
  'swot-generator',
  'business-model-canvas',
  'gantt-chart',
  'kanban',
  'gallup-kompasrose',
  'tows-matrix',
  'porters-five-forces',
  'value-proposition-canvas',
  'empathy-map',
  'card-sorting',
  'smuk-model',
  'smp-model',
  'aaker-identity-model',
  'survey-template',
  'affinity-diagram',
  'scamper',
  'hmw',
  'five-whys',
  'brugerrejse',
  'dikw-pyramiden',
  'brainstorming',
  'pestel',
  'peso',
  'golden-circle',
  'persona-canvas',
  'pirate-funnel',
  'service-blueprint',
  'seo-pyramide',
  'strategisk-afvejning',
  'aida-funnel',
  'dvf-venn-model',
] as const

export type ToolSlug = (typeof TOOL_SLUGS)[number]
